def returnResponse(responseCode):
    responseCodes = {
        101: "HTTPS not used",
        102: "No version specified",
        103: "Invalid API version",
        104: "No type specified",
        105: "Invalid API type",
        106: "No operation specified",
        107: "Invalid API operation",
        108: "Missing parameters for the specified operation",
        109: "No API key specified",
        110: "Invalid API key",
        111: "Invalid User",
        112: "API not available to Sub-Accounts",
        113: "This API account cannot be accessed from your IP",
        114: "Invalid Domain Syntax",
        115: "Central Registry Not Responding - try again later",
        116: "Invalid sandbox account",
        117: "The provided credit card profile either does not exist, or is not associated with your account",
        118: "The provided credit card profile has not been verified",
        119: "Insufficient account funds for requested transaction",
        120: "API key must be passed as a GET",
        200: "Domain is not active, or does not belong to this user",
        201: "Internal System error",
        210: 210,
        250: "Domain is already set to AutoRenew - No update made.",
        251: "Domain is already set not to AutoRenew - No update made.",
        252: "Domain is already Locked - No update made.",
        253: "Domain is already Unlocked - No update made.",
        254: 254,
        255: "Domain is already Unlocked - No update made.",
        256: "Domain is already Not Private - No update made.",
        261: 261,
        262: "This domain is already active within our system and therefore cannot be processed.",
        263: "Invalid number of years, or no years provided.",
        264: 264,
        265: 265,
        266: "No domain transfer exists for this user for this domain",
        267: "Invalid domain name, or we do not support the provided extension/TLD.",
        280: "DNS modification error",
        300: 300,
        301: 301,
        302: 302,
        400: "Existing API request is still processing - request will need to be re-submitted"
    }
    return responseCodes.get(responseCode, f"Got error code: ({responseCode})!! \nBut there is no error code like this in this program!!")
